services:
  nextjs:
    build: ./nextjs
    container_name: nextjs
    networks:
      - frontend
    expose:
      - 3000

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    depends_on:
      - nextjs
    networks:
      - frontend

  certbot:
    image: certbot/dns-cloudflare
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./cloudflare.ini:/cloudflare.ini:ro
    command: certonly --dns-cloudflare --dns-cloudflare-credentials /cloudflare.ini --dns-cloudflare-propagation-seconds 30 -d next.pace11.my.id --agree-tos --non-interactive -m rppratama1771@email.com

networks:
  frontend:
