name: Deployment Docker Compose

on:
  push:
    tags:
      - v**

jobs:
  run-build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Docker Compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd pace-app
            sudo rm -rf .env
            echo "${{ secrets.ENV_PROD }}" | sudo tee .env > /dev/null
            sudo git pull origin master
            sudo docker compose down
            sudo docker compose up -d
            sudo docker ps
